name: Update Sitemap

on:
  push:
    paths:
      - 'public/articles/**'
  workflow_dispatch:

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Generate sitemap
      run: |
        cat > generate-sitemap.js << 'EOF'
        const fs = require('fs');
        const path = require('path');

        function escapeXml(text) {
          return text
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&apos;');
        }
        
        async function generateSitemap() {
          try {
            const baseUrl = 'https://tu-dominio.com'; // Cambiar por tu dominio
            const currentDate = new Date().toISOString();
            
            let sitemap = `<?xml version="1.0" encoding="UTF-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
                xmlns:xhtml="http://www.w3.org/1999/xhtml"
                xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
            `;
            
            // Agregar página principal
            sitemap += `
          <url>
            <loc>${baseUrl}</loc>
            <lastmod>${currentDate}</lastmod>
            <changefreq>daily</changefreq>
            <priority>1.0</priority>
          </url>`;
            
            // Agregar páginas estáticas
            const staticPages = [
              { path: '/sobre-nosotros', priority: '0.8', changefreq: 'monthly' },
              { path: '/contacto', priority: '0.8', changefreq: 'monthly' }
            ];
            
            staticPages.forEach(page => {
              sitemap += `
          <url>
            <loc>${baseUrl}${page.path}</loc>
            <lastmod>${currentDate}</lastmod>
            <changefreq>${page.changefreq}</changefreq>
            <priority>${page.priority}</priority>
          </url>`;
            });
            
            // Leer artículos del índice
            try {
              const articlesIndexPath = 'public/articles/index.json';
              if (fs.existsSync(articlesIndexPath)) {
                const articlesData = fs.readFileSync(articlesIndexPath, 'utf8');
                const articles = JSON.parse(articlesData);

                console.log(`Processing ${articles.length} articles for sitemap...`);

                // Validar y procesar artículos
                const validArticles = articles.filter(article =>
                  article &&
                  article.slug &&
                  article.title &&
                  article.publishedAt &&
                  article.tags &&
                  Array.isArray(article.tags)
                );

                console.log(`${validArticles.length} valid articles found`);

                validArticles.forEach((article, index) => {
                  try {
                    const articleDate = new Date(article.publishedAt).toISOString();
                    const escapedTitle = escapeXml(article.title);
                    const escapedKeywords = escapeXml(article.tags.join(', '));

                    sitemap += `
          <url>
            <loc>${baseUrl}/articulo/${encodeURIComponent(article.slug)}</loc>
            <lastmod>${articleDate}</lastmod>
            <changefreq>weekly</changefreq>
            <priority>0.9</priority>
            <news:news>
              <news:publication>
                <news:name>DevTips</news:name>
                <news:language>es</news:language>
              </news:publication>
              <news:publication_date>${articleDate}</news:publication_date>
              <news:title>${escapedTitle}</news:title>
              <news:keywords>${escapedKeywords}</news:keywords>
            </news:news>
          </url>`;

                    // Log progress for large numbers of articles
                    if ((index + 1) % 10 === 0) {
                      console.log(`Processed ${index + 1}/${validArticles.length} articles`);
                    }
                  } catch (articleError) {
                    console.warn(`Error processing article ${article.slug}:`, articleError.message);
                  }
                });

                console.log(`✅ Added ${validArticles.length} articles to sitemap`);
              } else {
                console.log('📁 Articles index file not found');
              }
            } catch (error) {
              console.error('❌ Error reading articles index:', error.message);
              console.log('Creating sitemap with static pages only');
            }
            
            sitemap += `
        </urlset>`;
            
            // Escribir sitemap
            fs.writeFileSync('public/sitemap.xml', sitemap);
            
            // Generar robots.txt
            const robotsTxt = `User-agent: *
        Allow: /
        
        Sitemap: ${baseUrl}/sitemap.xml
        
        # Disallow admin or private areas
        Disallow: /admin/
        Disallow: /.github/
        Disallow: /templates/
        
        # Allow articles
        Allow: /articulo/
        Allow: /articles/
        `;
            
            fs.writeFileSync('public/robots.txt', robotsTxt);
            
            console.log('Sitemap and robots.txt generated successfully');
            console.log(`Sitemap includes ${sitemap.split('<url>').length - 1} URLs`);
            
          } catch (error) {
            console.error('Error generating sitemap:', error);
            process.exit(1);
          }
        }
        
        generateSitemap();
        EOF
        
        node generate-sitemap.js
        
    - name: Commit and push sitemap
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/sitemap.xml public/robots.txt
        git commit -m "🗺️ Update sitemap and robots.txt" || exit 0
        git push
